#!/usr/bin/env python2

from orthrus.commands import *
from orthrusutils.orthrusutils import *

DESCRIPTION = """A tool for extended analysis of fuzzed applications."""

class OrthrusTool():
    def __init__(self, description, args):
        self._description = description
        self._args = parse_cmdline(description, args, self._create,
                                   self._add, self._remove,
                                   self._start, self._stop, self._show,
                                   self._triage, self._database,
                                   self._clean, self._destroy)
        self._config = parse_config()

    def _create(self, args):
        cmd = OrthrusCreate(args, self._config)
        cmd.run()

    def _add(self, args):
        cmd = OrthrusAdd(args, self._config)
        cmd.run()

    def _remove(self, args):
        cmd = OrthrusRemove(args, self._config)
        cmd.run()

    def _start(self, args):
        cmd = OrthrusStart(args, self._config)
        cmd.run()

    def _stop(self, args):
        cmd = OrthrusStop(args, self._config)
        cmd.run()

    def _show(self, args):
        cmd = OrthrusShow(args, self._config)
        cmd.run()

    def _triage(self, args):
        cmd = OrthrusTriage(args, self._config)
        cmd.run()

    def _database(self, args):
        cmd = OrthrusDatabase(args, self._config)
        cmd.run()

    def _clean(self, args):
        color_print(bcolors.INFO, "Not implemented")
        pass

    def _destroy(self, args):
        cmd = OrthrusDestroy(args, self._config)
        cmd.run()

    def run(self):
        sys.stdout.write(self._description + "\n\n")

        self._args.func(self._args)

if __name__ == '__main__':
    tool = OrthrusTool(DESCRIPTION, sys.argv[1:])
    tool.run()